/**
 * Build-time sitemap generator.
 *
 * Runs AFTER the prerender script. Reads the URL list from
 * dist/sitemap-urls.json (generated by prerender-shows.mjs) and
 * writes dist/sitemap.xml with all static, show, and episode URLs.
 *
 * If dist/sitemap-urls.json is missing (e.g., prerender failed),
 * falls back to a minimal sitemap with just static + show pages.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const DIST = resolve(root, 'dist');

const BASE_URL = 'https://goodmorningbitcoin.com';
const currentDate = new Date().toISOString().split('T')[0];

// Determine priority and changefreq from URL
function urlMetadata(url) {
  if (url === `${BASE_URL}/`) return { changefreq: 'daily', priority: '1.0' };
  if (url.startsWith(`${BASE_URL}/shows`)) return { changefreq: 'daily', priority: '0.9' };
  if (url.startsWith(`${BASE_URL}/community`)) return { changefreq: 'weekly', priority: '0.8' };
  if (url.startsWith(`${BASE_URL}/podcast/`) && url.includes('/episode/')) return { changefreq: 'weekly', priority: '0.6' };
  if (url.startsWith(`${BASE_URL}/podcast/`)) return { changefreq: 'weekly', priority: '0.8' };
  if (url.startsWith(`${BASE_URL}/about`)) return { changefreq: 'monthly', priority: '0.7' };
  if (url.startsWith(`${BASE_URL}/schedule`)) return { changefreq: 'weekly', priority: '0.6' };
  return { changefreq: 'monthly', priority: '0.5' };
}

// Try to read the URL list from prerender
const urlsPath = resolve(DIST, 'sitemap-urls.json');
let urls;

if (existsSync(urlsPath)) {
  urls = JSON.parse(readFileSync(urlsPath, 'utf-8'));
  console.log(`[sitemap] Read ${urls.length} URLs from ${urlsPath}`);
} else {
  // Fallback: generate from shows.json
  console.warn('[sitemap] sitemap-urls.json not found — using fallback');
  const showsPath = resolve(root, 'public/shows.json');
  const shows = JSON.parse(readFileSync(showsPath, 'utf-8'));
  const staticPages = ['/', '/shows', '/about', '/schedule', '/community'];
  urls = [
    ...staticPages.map(p => `${BASE_URL}${p}`),
    ...shows
      .filter(s => s.podcastXml)
      .map(s => `${BASE_URL}/podcast/${encodeURIComponent(s.title.toLowerCase().replace(/\s+/g, '-'))}`),
  ];
}

// Build XML
const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(url => {
  const meta = urlMetadata(url);
  return `  <url>
    <loc>${url}</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>${meta.changefreq}</changefreq>
    <priority>${meta.priority}</priority>
  </url>`;
}).join('\n')}
</urlset>
`;

const outputPath = resolve(DIST, 'sitemap.xml');
writeFileSync(outputPath, xml, 'utf-8');
console.log(`[sitemap] Generated sitemap with ${urls.length} URLs → ${outputPath}`);
